currdir=$(shell pwd)
builddir=${currdir}/build
downloadsdir=$(shell cd ~; realpath -m ./downloads)
repodir=$(builddir)/bin
repo=$(repodir)/repo
repourl=http://commondatastorage.googleapis.com/git-repo-downloads/repo
repogiturl=https://gerrit.googlesource.com/git-repo
yoctodir=$(builddir)/yocto
yoctourl=https://github.com/Advantech-IIoT/yocto.git
yoctobranch=project/tpc71wn10pa
yoctomanifest=default.xml
yoctomachine=imx6dltpc71wn10pa
yoctobuilddir=build.$(yoctomachine)
yoctodistro=x11
SHELL=/bin/bash
export YOCTO_DL_DIR="/root/$(yoctomachine)/downloads"
export YOCTO_TMPDIR="/root/$(yoctomachine)/tmp"
export YOCTO_SSTATE_DIR="/root/$(yoctomachine)/sstate-cache"
